import {
  TYPES_OF_HOW_TO_FIND,
  TYPES_OF_PERSONAL_TITLE,
  TYPES_OF_SUBJECT,
} from 'constants/options';

export const REGISTER_FORM_FIELDS = {
  TYPE: 'type',
  FIRST_NAME: 'firstname',
  LAST_NAME: 'lastname',
  PHONE: 'phonenumber',
  EMAIL: 'email',
  BIRTHDAY: 'birthday',
  NATIONAL_ID: 'nationalid',
  COMPANY_NAME: 'companyname',
  TAX_ID: 'taxid',
  ADDRESS_1: 'address1',
  CITY: 'city',
  STATE: 'state',
  COUNTRY: 'country',
  PASSWORD: 'password',
  CURRENCY: 'currency',

  // TODO: update later
  PERSONAL_TITLE: 'title',
  HOW_TO_FIND: 'howToFind',
  RECAPTCHA: 'reCaptcha',
};

export const INITIAL_VALUES = {
  [REGISTER_FORM_FIELDS.TYPE]: TYPES_OF_SUBJECT.PERSONAL.value,
  [REGISTER_FORM_FIELDS.FIRST_NAME]: '',
  [REGISTER_FORM_FIELDS.LAST_NAME]: '',
  [REGISTER_FORM_FIELDS.PHONE]: '',
  [REGISTER_FORM_FIELDS.EMAIL]: '',
  [REGISTER_FORM_FIELDS.BIRTHDAY]: '',
  [REGISTER_FORM_FIELDS.NATIONAL_ID]: '',
  [REGISTER_FORM_FIELDS.COMPANY_NAME]: '',
  [REGISTER_FORM_FIELDS.TAX_ID]: '',
  [REGISTER_FORM_FIELDS.ADDRESS_1]: '',
  [REGISTER_FORM_FIELDS.CITY]: '',
  [REGISTER_FORM_FIELDS.STATE]: '',
  [REGISTER_FORM_FIELDS.COUNTRY]: '',
  [REGISTER_FORM_FIELDS.PASSWORD]: '',
  [REGISTER_FORM_FIELDS.CURRENCY]: '',

  [REGISTER_FORM_FIELDS.PERSONAL_TITLE]: TYPES_OF_PERSONAL_TITLE.NONE.value,
  [REGISTER_FORM_FIELDS.HOW_TO_FIND]: TYPES_OF_HOW_TO_FIND.FACEBOOK.value,
  [REGISTER_FORM_FIELDS.RECAPTCHA]: '',
};
