// TODO: Update schema
// {
//   "id": 11,
//   "category_id": "4",
//   "type": "1",
//   "name": "Starter Hosting",
//   "paytype": "Regular",
//   "description": "<ul></ul>",
//   "tax_group_id": "1",
//   "out_of_stock": false,
//   "tags": [],
//   "stock": false,
//   "qty": 0,
//   "periods": [
//       {
//           "title": "Monthly",
//           "formatted": "Monthly ",
//           "value": "m",
//           "price": "5",
//           "setup": 0,
//           "selected": true
//       },
//       {
//           "title": "Triennially",
//           "formatted": "Triennially -99% discount",
//           "value": "t",
//           "price": "2",
//           "setup": 0,
//           "selected": false
//       }
//   ]
// }

export const hostingData = [
  {
    type: 'cloudHosting',
    products: [
      {
        favorite: false,
        name: 'Host SSD 100MB',
        capacity: '100MB',
        price: '9,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 100MB</b>',
          'Addon domain <b>0</b>',
          'Subdomain <b>không giới hạn</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>512MB</b>',
          'CPU <b>1 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: false,
        name: 'Host SSD 1GB',
        capacity: '1GB',
        price: '59,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 1GB</b>',
          'Addon domain <b>1</b>',
          'Subdomain <b>không giới hạn</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>768MB</b>',
          'CPU <b>1 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: false,
        name: 'Host SSD 2GB',
        capacity: '2GB',
        price: '89,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 2GB</b>',
          'Addon domain <b>2</b>',
          'Subdomain <b>không giới hạn</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>1GB</b>',
          'CPU <b>1 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: true,
        name: 'Host SSD 4GB',
        capacity: '4GB',
        price: '139,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 4GB</b>',
          'Addon domain <b>4</b>',
          'Subdomain <b>không giới hạn</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>1.5GB</b>',
          'CPU <b>1 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: false,
        name: 'Host SSD 6GB',
        capacity: '6GB',
        price: '199,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 6GB</b>',
          'Addon domain <b>6</b>',
          'Subdomain <b>không giới hạn</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>2GB</b>',
          'CPU <b>2 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: false,
        name: 'Host SSD 8GB',
        capacity: '8GB',
        price: '239,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 8GB</b>',
          'Addon domain <b>8</b>',
          'Subdomain <b>không giới hạn</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>2.5GB</b>',
          'CPU <b>2 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
    ],
  },
  {
    type: 'cloudHostingBusiness',
    products: [
      {
        favorite: false,
        name: 'Business SSD 10 GB',
        capacity: '10GB',
        price: '319,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 10GB</b>',
          'Số lượng website <b>15</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>2GB</b>',
          'CPU <b>2 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: false,
        name: 'Business SSD 20 GB',
        capacity: '20GB',
        price: '419,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 20GB</b>',
          'Số lượng website <b>30</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>2.5GB</b>',
          'CPU <b>3 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
      {
        favorite: false,
        name: 'Business SSD 40 GB',
        capacity: '40GB',
        price: '759,000',
        unit: 'đ',
        contents: [
          'Dung lượng đĩa <b>SSD 40GB</b>',
          'Số lượng website <b>50</b>',
          'Băng thông <b>không giới hạn</b>',
          'Ram <b>3GB</b>',
          'CPU <b>4 core</b>',
          'Backup <b>hàng ngày</b> ',
          'Hỗ trợ <b>24/7 chuyên nghiệp</b>',
          '<b>cPanel</b> mạnh mẽ đi cùng với <b>Litespeed webserver, Cloudlinux</b>',
          'Diệt mã độc tự động <b> Imunify360 </b>',
          '<b>Litespeed Memcache</b>',
          'Chứng chỉ <b>SSL miễn phí</b> để đảm bảo an toàn cho dữ liệu người dùng &amp; tăng hạng SEO.',
        ],
      },
    ],
  },
];
