export const ERR_IS_EXIST = 'SYM.EXISTING_SESSION';
export const OLD_PASSWORD = 'SYM.OLD_PASSWORD_DETECTED';
export const DF_PASSWORD = 'SYM.DEFAULT_PASSWORD_DETECTED';
export const EXISTING_SESSION = 'SYM.EXISTING_SESSION';
export const INVALID_SESSION = 'SYM.INVALID_SESSION';
export const HAVE_BEEN_KICKED_OUT = 'SYM.HAVE_BEEN_KICKED_OUT';
export const INVALID_SESSION_TIMEOUT = '1000';
